# Time, Datetime, Delta

In [1]:
import datetime as dt
import time as time

In [2]:
dt_now = dt.datetime.fromtimestamp(time.time())

In [3]:
dt_now

datetime.datetime(2021, 6, 28, 17, 57, 27, 378716)

In [4]:
dt_now.day

28

In [5]:
dt_now.month

6

In [6]:
delta = dt.timedelta(days=100)
delta

datetime.timedelta(days=100)

In [7]:
dt_now + delta

datetime.datetime(2021, 10, 6, 17, 57, 27, 378716)

In [8]:
today = dt.date.today()
today

datetime.date(2021, 6, 28)

In [9]:
today + delta

datetime.date(2021, 10, 6)

# Objects and map()

In [10]:
class Person:
    department = 'School of information'
    
    def set_name(self, new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [11]:
store1 = [6,5,6,7,7,5]
store2 = [3,6,7,4,7]
cheapest = map(min, store1, store2)
cheapest

In [12]:
list(cheapest)

[3, 5, 6, 4, 7]

In [13]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split(' ', 1)

list(map(split_title_and_name, people))

[['Dr.', 'Christopher Brooks'],
 ['Dr.', 'Kevyn Collins-Thompson'],
 ['Dr.', 'VG Vinod Vydiswaran'],
 ['Dr.', 'Daniel Romero']]

In [14]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split(' ', 2)[2]

list(map(split_title_and_name, people))


['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vinod Vydiswaran', 'Dr. Romero']

# Advanced Python Lambda and List Comprehensions

In [15]:
my_func = lambda a, b, c: a+b

In [16]:
my_func(1, 2 , 3)

3

In [17]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0]+' '+x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0]+' '+person.split()[-1], people))


True
True
True
True


True

In [18]:
my_list = list()
for n in range(0,1000):
    if n%2 == 0:
        my_list.append(n)


In [19]:
my_list = [n for n in range(0,1000) if n%2==0]

# Numpy

In [61]:
import numpy as np
import math

In [22]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [24]:
b = np.array([1,2,3])
c = np.array([a, b])
c

array([[1, 2, 3],
       [1, 2, 3]])

In [25]:
c.shape

(2, 3)

In [26]:
c.dtype

dtype('int64')

In [27]:
d = np.array([1.0,2.0,3.0])
d.dtype

dtype('float64')

In [32]:
os = np.zeros((2,4))
print(os)

ones = np.ones((2,4))
print(ones)

eye = np.eye(3)
print(eye)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
np.random.rand(3,4)

array([[0.70440602, 0.62720044, 0.69047196, 0.62615401],
       [0.42796825, 0.35940754, 0.73634782, 0.05235658],
       [0.87957191, 0.67545571, 0.72039482, 0.11257829]])

In [40]:
arr = np.arange(10,50,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45])

In [41]:
arr1 = np.linspace(10,50,7)
arr1

array([10.        , 16.66666667, 23.33333333, 30.        , 36.66666667,
       43.33333333, 50.        ])

## Array Operations

In [42]:
a + b

array([2, 4, 6])

In [43]:
a - b

array([0, 0, 0])

In [44]:
a * b

array([1, 4, 9])

In [45]:
[a]

[array([1, 2, 3])]

In [46]:
list(a)

[1, 2, 3]

In [47]:
c >= 2

array([[False,  True,  True],
       [False,  True,  True]])

In [49]:
a1 = np.random.rand(3,3)
print(a1)

a2 = np.eye(3)
print(a2)

print(a1 * a2)
print(a1 @ a2)

[[0.4673439  0.02436713 0.19091207]
 [0.17369774 0.74405197 0.22497246]
 [0.27682062 0.41317171 0.49161601]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.4673439  0.         0.        ]
 [0.         0.74405197 0.        ]
 [0.         0.         0.49161601]]
[[0.4673439  0.02436713 0.19091207]
 [0.17369774 0.74405197 0.22497246]
 [0.27682062 0.41317171 0.49161601]]


In [50]:
a1.T

array([[0.4673439 , 0.17369774, 0.27682062],
       [0.02436713, 0.74405197, 0.41317171],
       [0.19091207, 0.22497246, 0.49161601]])

In [51]:
a1.shape

(3, 3)

In [53]:
print((a1 * a2).dtype)
print((a1 @ a2).dtype)

float64
float64


In [54]:
print(a1.sum())
print(a1.min())
print(a1.max())
print(a1.mean())

3.006953614348062
0.024367132226507437
0.74405197010804
0.33410595714978464


In [55]:
c.shape

(2, 3)

In [56]:
c.reshape(1,6)

array([[1, 2, 3, 1, 2, 3]])

In [62]:
c.reshape(1,6).T

array([[1],
       [2],
       [3],
       [1],
       [2],
       [3]])

In [57]:
c

array([[1, 2, 3],
       [1, 2, 3]])

In [61]:
c.reshape(6)

array([1, 2, 3, 1, 2, 3])

In [64]:
from PIL import Image
from IPython.display import display

In [ ]:
# im = Image.open('some_image.png')
# display(im)

In [68]:
f = np.full((3,3), 10)
f

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [70]:
k = f - a1.T
k

array([[9.5326561 , 9.82630226, 9.72317938],
       [9.97563287, 9.25594803, 9.58682829],
       [9.80908793, 9.77502754, 9.50838399]])

In [73]:
k.astype(np.uint8)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]], dtype=uint8)

## Indexing, slicing, iterating

In [76]:
print(k)
for a in k:
    print(a)

[[9.5326561  9.82630226 9.72317938]
 [9.97563287 9.25594803 9.58682829]
 [9.80908793 9.77502754 9.50838399]]
[9.5326561  9.82630226 9.72317938]
[9.97563287 9.25594803 9.58682829]
[9.80908793 9.77502754 9.50838399]


In [77]:
k[2]

array([9.80908793, 9.77502754, 9.50838399])

In [79]:
k[1,1]

9.25594802989196

In [80]:
k

array([[9.5326561 , 9.82630226, 9.72317938],
       [9.97563287, 9.25594803, 9.58682829],
       [9.80908793, 9.77502754, 9.50838399]])

In [81]:
k[k>9.5]

array([9.5326561 , 9.82630226, 9.72317938, 9.97563287, 9.58682829,
       9.80908793, 9.77502754, 9.50838399])

## Slicing

In [82]:
arr = (np.random.rand(3,5) * 100).astype(int)

In [83]:
arr

array([[27, 28, 35, 59, 54],
       [76, 31, 47, 32, 64],
       [ 2, 69, 94, 64, 41]])

In [85]:
arr[:2,:3]

array([[27, 28, 35],
       [76, 31, 47]])

In [86]:
arr[:,2:4]

array([[35, 59],
       [47, 32],
       [94, 64]])

## Try Numpy with Datasets

In [87]:
for i in range(0,arr.shape[1]):
    print(arr[:,i])
    print()

[27 76  2]

[28 31 69]

[35 47 94]

[59 32 64]

[54 64 41]



In [88]:
arr

array([[27, 28, 35, 59, 54],
       [76, 31, 47, 32, 64],
       [ 2, 69, 94, 64, 41]])

In [89]:
arr[:,2:4]

array([[35, 59],
       [47, 32],
       [94, 64]])

In [90]:
arr[1:3,:]

array([[76, 31, 47, 32, 64],
       [ 2, 69, 94, 64, 41]])

In [91]:
arr[:,[1,3]]

array([[28, 59],
       [31, 32],
       [69, 64]])

In [93]:
arr[:2]

array([[27, 28, 35, 59, 54],
       [76, 31, 47, 32, 64]])

In [94]:
arr[:,:2]

array([[27, 28],
       [76, 31],
       [ 2, 69]])

In [95]:
arr

array([[27, 28, 35, 59, 54],
       [76, 31, 47, 32, 64],
       [ 2, 69, 94, 64, 41]])

In [101]:
arr1 = arr[arr > 40]
arr1

array([59, 54, 76, 47, 64, 69, 94, 64, 41])

In [102]:
arr.mean()

48.2

In [103]:
arr[arr>50].mean()

68.57142857142857

# Regex

In [2]:
import re

In [3]:
txt = 'This is a good day!|'

In [5]:
if re.search('good', txt):
    print('yes!')

yes!


In [7]:
if re.search('god', txt):
    print('yes!')
else:
    print('no!')

no!


In [8]:
txt = 'My name is Gogo. My cat\'s name is Momo. Our names are beautiful'

In [9]:
re.findall('name',txt)

['name', 'name', 'name']

In [10]:
re.split('name',txt)

['My ', " is Gogo. My cat's ", ' is Momo. Our ', 's are beautiful']

In [11]:
# ^ - start
# $ - end

bool(re.search('^Momo',txt))

False

In [12]:
bool(re.search('beautiful$',txt))

True

## Pattern and character classes

In [25]:
grades = 'ACBCABCBCBABCAAABACAABC'

In [15]:
len(re.findall('ABC',grades))

3

In [16]:
# [] - one of / in range
re.findall('[AB]',grades)

['A', 'B', 'A', 'B', 'B', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B']

In [18]:
re.findall('A[BC][B-C]', grades)

['ACB', 'ABC', 'ABC', 'ABC']

In [20]:
# | - OR

re.findall('AA|AC|BC', grades)

['AC', 'BC', 'BC', 'BC', 'BC', 'AC', 'BC']

In [21]:
# ^ inside [] means NOT

re.findall('[^C]', grades)

['A', 'B', 'A', 'B', 'B', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B']

In [23]:
re.findall('^[^C]',grades)

['A']

## Quantifiers

In [26]:
# X{M,N} - M as max and N as min repetition of X

re.findall('A{2,10}',grades)

['AAA', 'AA']

In [28]:
re.findall('A{1,1}A{1,1}',grades)

['AA', 'AA']

In [29]:
re.findall('AA',grades)

['AA', 'AA']

In [ ]:
# X{M} means exact this number M of repetitions of X

In [30]:
re.findall('A{3}',grades)

['AAA']

In [ ]:
# with open('file.txt','r') as file:
#     info=file.read()

In [32]:
grades

'ACBCABCBCBABCAAABACAABC'

In [33]:
# \w means any letter, including digits and numbers
re.findall('[\w]{1,7}',grades)

['ACBCABC', 'BCBABCA', 'AABACAA', 'BC']

In [ ]:
# * - aterix means match 0 or more times

In [34]:
g = 'Aab ca AB aABbC AbcD a BCda'

In [41]:
re.findall('a*[\w]{2,4}', g)

['Aab', 'ca', 'AB', 'aABbC', 'AbcD', 'BCda']

In [56]:
re.split('[ ]*a[ ]*|[ ]',g)

['A', 'b', 'c', 'AB', 'ABbC', 'AbcD', 'BCd', '']

## Groups

In [ ]:
# For groups brackets () are used, they provide a tuple of elements in regex match

In [ ]:
# ?P means this is an extension to basic regex

## Look-ahead and look-behind

In [ ]:
# When we want to find all occurrences of text before/after some pattern, but don't want the pattern to be included, 
# we use the following approach:
# Just add ?= before the pattern

In [59]:
re.findall('[\w]*(?=\s)',g)

['Aab', '', 'ca', '', 'AB', '', 'aABbC', '', 'AbcD', '', 'a', '']

In [65]:
a = np.array([1,2,3,4,5,6,7])
a.reshape(7,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [66]:
np.linspace(1,4,4)

array([1., 2., 3., 4.])

In [68]:
np.random.rand(4)

array([0.66089004, 0.80457769, 0.25667767, 0.66629009])

In [69]:
np.array([[3,4,5]])

array([[3, 4, 5]])

In [70]:
np.arange(1,4,1)

array([1, 2, 3])